### ISSUE TITLE
Segfault when application is closed while connecting

### ISSUE THREAD

**Issue by PerryWerneck** [PerryWerneck/lib3270#13]
Lib3270 segfaults when the application is closed while connecting. The lib3270 cleanup procedure should wait for background thread.

`
#0  0x00007f2f6097ff7a in net_disconnect (hSession=0x555d59937810) at src/core/telnet.c:492
#1  0x00007f2f6098bb84 in host_disconnect (hSession=<optimized out>, hSession@entry=0x555d59937810, failed=failed@entry=0) at src/core/host.c:126
#2  0x00007f2f6098bc27 in lib3270_disconnect (h=h@entry=0x555d59937810) at src/core/host.c:108
#3  0x00007f2f6099d6c7 in net_reconnect (hSession=0x555d59937810, seconds=<optimized out>) at src/core/linux/connect.c:295
#4  0x00007f2f60bdead8 in  () at /usr/lib64/libv3270.so.5.4
#5  0x00007f2f60e73e47 in  () at /usr/lib64/libglib-2.0.so.0
#6  0x00007f2f60e77464 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#7  0x00007f2f60e77800 in  () at /usr/lib64/libglib-2.0.so.0
#8  0x00007f2f60e7788c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#9  0x00007f2f6168484d in g_application_run () at /usr/lib64/libgio-2.0.so.0
#10 0x0000555d58d57bd8 in main (argc=1, argv=0x7ffefb791998) at src/main/main.c:115
`

**Comment by PerryWerneck** [comment]
Fixed on development versions; will be on the next merge.

- lib3270: New method to get the number of active background tasks.
- libv3270: Delaying session cleanup until there's no active background task.
